version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile_front
      context: ./
    volumes:
      - ./rush01-front:/app
    ports:
      - "3000:3000"
    depends_on: 
      - backend
  backend:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./rush01-back:/app
    ports:
      - "4200:4200"
    depends_on: 
