version: "3"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - .:/app
    ports:
      - "4200:4200"
    depends_on: 
      - mysql
  mysql: # 서비스 명
    image: mysql:latest # 사용할 이미지
    container_name: mysql_database2 # 컨테이너 이름 설정
    environment: # -e 옵션
      MYSQL_DATABASE: 42overflow
      MYSQL_ROOT_PASSWORD: 1234  # MYSQL 패스워드 설정 옵션
      MYSQL_TCP_PORT: 5000
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mariadb:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)
    network_mode: "host"